### ISSUE TITLE
Add player name input and display in every turn for Tic-Tac-Toe game

### ISSUE THREAD

**Issue by johnslak** [mohammedyashour/tic_tac_toe_python#1]
The current Tic-Tac-Toe game code only allows for "X" and "O" as the players, but it would be more user-friendly to allow for players to input their own names. Additionally, it would be helpful to display the current player's name in every turn.

Steps to Reproduce:

    Run the current Tic-Tac-Toe game code
    Observe that there is no input for player names and no display of player names in each turn

Expected behavior:

    Allow for player input of their own names at the start of the game
    Display the current player's name in every turn

Additional context:
This modification would enhance the user experience and add a personal touch to the game.

Labels: enhancement, name input, game display

Assignees: @Moudyash

**Comment by mohammedyashour** [comment]
Thanks for bringing this up! I have made the necessary changes to the code and now players can input their own names at the start of the game. Additionally, the current player's name is displayed in every turn. I've also added some comments to the code to make it more readable.

I have tested the code and it seems to be working as expected. I've also added some input validation to handle any invalid inputs from the player.

I've created a pull request for the changes. Please review the code and let me know if there are any issues or further changes required.

Thanks for your contributions!
